# Generated by Django 5.1.3 on 2024-11-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pixels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('canvas_id', models.IntegerField()),
                ('pixel_x', models.IntegerField()),
                ('piexl_y', models.IntegerField()),
                ('pixel_color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
    ]
