# Generated by Django 5.1.3 on 2024-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='color_pallette9',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='color_pallette2',
            field=models.CharField(default='#ea6d57', max_length=7),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='color_pallette3',
            field=models.CharField(default='#ffdc80', max_length=7),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='color_pallette4',
            field=models.CharField(default='#ffe8f0', max_length=7),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='color_pallette5',
            field=models.CharField(default='#f0596a', max_length=7),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='color_pallette6',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='color_pallette7',
            field=models.CharField(default='#251832', max_length=7),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='color_pallette8',
            field=models.CharField(default='#feeaf3', max_length=7),
        ),
    ]
