# Generated by Django 5.1.3 on 2024-11-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='time_control',
            field=models.CharField(default='blitz', max_length=7),
        ),
    ]
