# Generated by Django 5.1.3 on 2024-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_alter_canvas_time_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='time_control',
            field=models.CharField(default='blitz', max_length=8),
        ),
    ]
