# Generated by Django 5.1.3 on 2024-11-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_canvas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixels',
            old_name='piexl_y',
            new_name='pixel_y',
        ),
    ]
