# Generated by Django 5.1.3 on 2024-11-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_alter_canvas_time_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='background_image',
            field=models.CharField(default='fallback.png', max_length=150),
        ),
        migrations.AddField(
            model_name='canvas',
            name='credits',
            field=models.CharField(default='No Credits', max_length=150),
        ),
    ]
