# Generated by Django 5.1.3 on 2024-11-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_canvas_background_image_canvas_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='background_image',
            field=models.ImageField(default='/srcs/fallback.png', max_length=150, upload_to='srcs/'),
        ),
    ]
